### ISSUE TITLE
  Smknstd\FakerPicsumImages\FakerPicsumImagesProvider::image(): Argument #4 ($isFullPath) must be of type bool, null given

### ISSUE THREAD

**Issue by LfJohnVo** [smknstd/fakerphp-picsum-images#1]
I follow all de tutorial but i get this

  Smknstd\FakerPicsumImages\FakerPicsumImagesProvider::image(): Argument #4 ($isFullPath) must be of type bool, null given

**Comment by smknstd** [comment]
Hello !

Can you show a code snippet ? I think the tutorial call image() with only 3 params so it uses the default value (true) for $isFullPath https://github.com/smknstd/fakerphp-picsum-images/blob/main/src/FakerPicsumImagesProvider.php#L50

**Comment by LfJohnVo** [comment]
I resolved using this :) 

`public function definition()
    {
        return [
            'image' => substr(FakerPicsumImagesProvider::image('public\storage\categories', 640, 480), 15)
        ];
    }`
