### ISSUE TITLE
Some images not download

### ISSUE THREAD

**Issue by zotarelli** [smknstd/fakerphp-picsum-images#3]
Hello!
Thanks for the package!
At first I used mmo/faker-images for fzaninotto/faker (deprecated ~ Oct 2020)
Then I find your package.

I have a curious, some images not download, only get an empty one. The same happen with the package mmo/faker-images.
Do you know why ocurr that behavior? Or have any clue what I doing wrong?

```php
$faker = \Faker\Factory::create();
$faker->addProvider(new \Smknstd\FakerPicsumImages\FakerPicsumImagesProvider($faker));

$path = 'public/storage/posts';

return [
    'url' => 'posts/' . $faker->image($path , 900, 300, false),
];
```

Of 100 images download only 67, and other 33 are not downloaded.

Thanks in advance for your help, Valeria.

**Comment by smknstd** [comment]
Hello @zotarelli Sorry I have no clue why you shouldn't get all your images from picsum. They probably limit their API usage but it should not be silent and I guess you should get an exception or something in such case.

**Comment by smknstd** [comment]
maybe you can open an issue in this repo https://github.com/DMarby/picsum-photos/issues or ask @DMarby directly ?

**Comment by zotarelli** [comment]
Hello @smknstd Thanks for your reply. I think the same, I think the same, if were a usage limit at API of picsum, not should finished silent. If I get an exception or something, I really don't see where to search. Anyway, I appreciate your time and I will ask to @DMarby.
Thanks!

**Comment by zotarelli** [comment]
Hello @smknstd
I figured out what happens. After ruling out that my version of curl is up to date and see that site picsum.photos have the ssl certificate up to date too, I tryed to use other connection to internet to discard a firewall. And that its!
I called to my ISP to see if they can fixed my issue, I'm waiting for a response yet.

Thanks and I'm sorry for the confusion!

**Comment by zotarelli** [comment]
You doing me had think when sayed "They probably limit their API usage but it should not be silent and I guess you should get an exception or something in such case"

I checked your FakerPicsumImagesProvider.php file, and have

```php
if (! $success) {
    unlink($filepath);

    // could not contact the distant URL or HTTP error - fail silently.
    return false;
}
```

I put an exception and then can see what happens, for example:

```php
if (! $success) {
    unlink($filepath);

    throw new \RuntimeException('Url: ' . $url . ' - Code Error httpReturnCode: '. $httpReturnCode . ' - curl_error: '. curl_error($ch) . ' - curl_errno: ' . curl_errno($ch));
}
```
With this exception I could saw whats happens, the error sayed me:

```php
RuntimeException 

  Url: https://picsum.photos/900/300?random=59466 - Code Error httpReturnCode: 302 - curl_error: OpenSSL SSL_connect: Connection reset by peer in connection to fastly.picsum.photos:443  - curl_errno: 35
```

Could you add some exception in that line? What do you think?

**Comment by zotarelli** [comment]
I forgot to mention in the before code example that `$httpReturnCode` is `curl_getinfo($ch, CURLINFO_HTTP_CODE)`

Leaving the code block like something like this:

```php
if (! $success) {
    unlink($filepath);

    $httpReturnCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    throw new \RuntimeException('Url: ' . $url . ' - Code Error httpReturnCode: '. $httpReturnCode . ' - curl_error: '. curl_error($ch) . ' - curl_errno: ' . curl_errno($ch));
}
```
We are in contact
